//! Versioned wire contract shared by the daemon and every Rust client.

pub mod events;
pub mod rpc;
pub mod types;

pub use events::{EditorEvent, EventLine};
pub use types::{
    AgentDefinition, Chat, ChatDetail, GetChatResult, Message, MessageDetail, MessagePart,
    MessagePartKind, MessageRole, MessageStatus, RunStatus, TurnStatus,
};

/// Increment when a wire change is not backward compatible.
pub const PROTOCOL_VERSION: u32 = 1;

/// Deterministic checked-in TypeScript contract consumed by the React app.
pub fn typescript_bindings() -> String {
    use ts_rs::TS;

    let config = ts_rs::Config::default();
    let declarations = [
        RunStatus::decl(&config),
        TurnStatus::decl(&config),
        MessageRole::decl(&config),
        MessageStatus::decl(&config),
        MessagePartKind::decl(&config),
        AgentDefinition::decl(&config),
        Chat::decl(&config),
        Message::decl(&config),
        MessagePart::decl(&config),
        MessageDetail::decl(&config),
        ChatDetail::decl(&config),
        GetChatResult::decl(&config),
        rpc::HealthResult::decl(&config),
        rpc::VersionResult::decl(&config),
        rpc::SubscribeEventsParams::decl(&config),
        rpc::CreateChatParams::decl(&config),
        rpc::ListChatsParams::decl(&config),
        rpc::GetChatParams::decl(&config),
        rpc::PromptParams::decl(&config),
        rpc::SetSessionModeParams::decl(&config),
        rpc::PromptResultDto::decl(&config),
        rpc::CancelResult::decl(&config),
        rpc::RespondAgentError::decl(&config),
        rpc::RespondAgentParams::decl(&config),
        rpc::RespondAgentResult::decl(&config),
        EditorEvent::decl(&config),
    ];

    format!(
        "// @generated by `cargo run -p amarcode-protocol --bin generate-protocol-types`\n\
         // Do not edit by hand.\n\n\
         export const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;\n\n\
         export type JsonValue = null | boolean | number | string | JsonValue[] | {{ [key: string]: JsonValue }};\n\n{}\n",
        declarations
            .into_iter()
            .map(|declaration| format!("export {declaration}"))
            .collect::<Vec<_>>()
            .join("\n\n")
    )
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    #[test]
    fn checked_in_typescript_bindings_are_current() {
        let checked_in = include_str!("../../application/src/generated/protocol.ts");
        let generated = super::typescript_bindings();

        assert_eq!(
            checked_in.replace("\r\n", "\n"),
            generated.replace("\r\n", "\n")
        );
    }

    #[test]
    fn serde_wire_shape_matches_the_generated_event_contract() {
        let event = super::EditorEvent::TurnUpdated {
            chat_id: "chat-1".into(),
            run_id: "run-1".into(),
            user_message_id: "message-1".into(),
            status: super::TurnStatus::Completed,
            stop_reason: Some("end_turn".into()),
            error_message: None,
        };

        assert_eq!(
            serde_json::to_value(event).expect("event must serialize"),
            json!({
                "type": "turnUpdated",
                "payload": {
                    "chat_id": "chat-1",
                    "run_id": "run-1",
                    "user_message_id": "message-1",
                    "status": "completed",
                    "stop_reason": "end_turn",
                    "error_message": null
                }
            })
        );
    }
}
